server:
  port: 8762

spring:
  application:
    name: provider-test

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    enabled: true