server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: gateway
<<<<<<< HEAD
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1
=======
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

>>>>>>> 6ee02b5cf3e426e48a828c84ba0da9c625477c96

zuul:
  ribbon:
    eager-load:
      enabled: true
  ingoredServices: '*'
  routes:
    consumer:
      path: /consumer/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      serviceId: consumer-test
      stripPrefix: true
    provider:
      path: /provider/**
      serviceId: provider-test
      stripPrefix: true

#ribbon:
#  eureka:
#    enabled: false
# zuul的routes功能并不会作为HystrixCommand，所以不会使用ribbon进行负载均衡，你需要指定静态的服务
# 另一种方法是禁止eureka的ribbon功能，自己实现ribbonClient
#hystrix:
#  command:
#    consumer-test:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
#
#consumer-test:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    ListOfServers: http://127.0.0.1:8764
#    ConnectTimeout: 1000
#    ReadTimeout: 3000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100