server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
#  cloud:
#    config:
#      server:
#        git:
#          url: https://xxx/xxx
#          force-pull: true