server:
  port: 8764

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,hystrix.stream

spring:
  application:
    name: consumer-test
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

feign:
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true
#management:
#  endpoint:
#    hystrix:
#      stream:
#        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/